<?php

echo '<h3>PRIVACY POLICY</h3>';
echo '<p><i>Last Updated November 19, 2023</i></p><br>';
echo '<div class="privacy" style="width: 90%; margin-left: 2rem; margin-right: auto;text-align: left;">';
echo '<p>Snoozelings is an asset of Slothie Studios. This privacy policy sets out how Slothie Studios uses and protects any information recieved when users interact with this website. This includes signing up, logging in, submitting information, and interacting with various portions of <a href="https://snoozelings.com/">https://snoozelings.com/</a>.<br><br>';
echo '<p>When submitting data to this website, it will only be used in accordance with the privacy policy below.</p><br>';
    echo '<p>We will never collect information we don\'t need, collect information from 3rd party websites, sell/lease/distribute information to 3rd party websites, or share your data with partner companies.</p><br>';
        echo '<p>The only time we will ever share your data is when required by a court of law or in accordance of law.<br><br></p>';
echo '<p style="text-align: center;"><strong>This policy may change at any time. <br>Please check this page every so often to ensure you agree with any changes.</strong></p><br>';
echo '<h4>What We Collect?</h4>';
echo '<p>We collect the following information at registration:<br><br>1. Email Address<br><br>2. Date of Birth<br><br>3. Pronouns<br><br>4. IP Addresses<br><br>What we collect during gameplay:<br><br>1. Generic Health Information <br><br>2. Medication Categories<br><br>3. Sleep Data</p>';
echo '<h4>What Do We Do With Gathered Information?</h4>';
echo '<p>We use your data for the following:<br><br>1. Internal Data Storage<br><br>2. Correspondance about your account including account activation, retrieving post passwords.<br><br>3. Your date of birth is used to check your age for registration, make sure you are 13 years or older, and deliver birthday rewards in-game.<br><br>4. IP addesses are used to monitor account activity and make sure users are following Terms of service, mainly the rules of one account per player.<br><br>5. Sleep Data is used to give rewards in-game<br><br>6. Medication data is used to give reminders to take your medication. We do not allow medication names to be enterred, only categories such as "heart burn medication", "depression medication", etc. <br><br>7. Health data is used for the health journaling feature. Only the user of the journal and owners can access this data. Still, we encourage users to not include personally identifiable data within your journal.</p>';
echo '<h4>Security</h4>';
echo '<p>We are doing all we can within our ability to protect your data. This includes measures run by our server hosts (siteground), encoding data like passwords, using SSL on all pages, and encouraging strong passwords. <br><br>You can read more about Siteground\'s security measures <a href="https://world.siteground.com/blog/siteground-security/">by clicking here.</a></p>';
echo '<h4>How We Use Cookies</h4>';
echo '<p>Cookies are small text files used to store user information on the user\'s computer. Cookies are essential to remembering data on your computer which is needed to keep you logged in. We also use it to store variables for your account including: account id, account username, and id of your main pet.<br><br>Cookies do not give us information in any way. The only information we get is the information you decide to share and enter within various parts of the website.<br><br>Most web browsers automatically accept cookies, but you can modify your settings. Though this will prevent the website from working as intended.</p>';
echo '<h4>Links To Other Websites</h4>';
echo '<p>This website may contain links to other websites on the bulletin boards, private messages, profiles, pet pages, etc. It also contains links to social media platforms run by Snoozelings<br><br>Once you leave our website through external links, please note that website will likely have different privacy policies. We have no control over the content you may encounter. <br><br>We are also not responsible for the privacy or protection of our members who have navigated away from the domain. </p>';
echo '<h4>How to Contact Us About Your Information</h4>';
echo '<p>If you would like to request deletion of your information, please email us at EMAIL. <br><br>If you would like to request your data, you may email EMAIL. <br><br>For either of the above inquiries, we may ask you to verify that you are the account owner by asking questions about your account.</p>';
echo '</div>';