<?php

echo '<h3>CODE OF CONDUCT</h3>';
echo '<p><i>Last Updated December 9th, 2023</i></p><br>';

echo '<div class="privacy" style="width: 90%; margin-left: 2rem; margin-right: auto;text-align: left;">';
echo '<p>Below is the Code of Conduct - <i>a set of rules that all players must abide by</i> - for <a href="index">https://snoozelings.com/</a>. By registering an account with Snoozelings, you agree to follow our Code of Conduct. By logging in and playing, you continuously agree to follow the code of conduct.<br><br>The Code of Conduct is in place to protect players and create a safe space, not to punish players. We want to create an easy environment where players can log on and take a break from the outside world. Our goal is to bring no harm to our players, whether by staff or fellow members.<br><br>The code of conduct applies to all facets of Snoozelings including but not limited to: the website, the official discord server, and our social media accounts. If you find someone breaking the code of conduct, please alert a moderator through our Moderator Mailbox feature. Do not try to police the issue yourself.<br><br>The code of conduct may be updated in the future. If this is done, there will be a sitewide announcement. You are urged to check this page every so often to be up to date on the current code. Exceptions will not be made for members who break the terms of service because they were not aware of policy changes.<br><br>If the code of conduct is broken, various actions may be taken by the developers. These may included but are not limited to: warnings, temporary bans, lifetime bans, ip bans, or restrictions of your account.</p>';
echo '<p style="text-align: center;"><strong><br>This policy may change at any time. <br>Please check this page every so often to ensure you agree with any changes.</strong></p><br>';
echo '<h4>Quick Links</h4>';
echo '<a href="#interactions" style="font-size:1.8rem">1. Player Interactions</a><br><br>';
echo '<a href="#artwork" style="font-size:1.8rem">2. Artwork Rules</a><br><br>';
echo '<a href="#account" style="font-size:1.8rem">3. Account Guidelines</a><br><br>';
echo '<a href="#scamming" style="font-size:1.8rem">4. Cheating & Scamming</a><br><br>';
echo '<a href="#roleplay" style="font-size:1.8rem">5. Roleplaying Restrictions</a><br><br>';
echo '<a href="#forbidden" style="font-size:1.8rem">6. Forbidden Topics</a><br><br>';
echo '<a href="#trading" style="font-size:1.8rem">7. Trading Regulations</a><br><br>';
echo '<h4 id="interactions">Player Interactions</h4><br>';
echo '<p><strong>1. Be respectful towards all members, including moderators and admins.</strong><br><br>We do not allow any disrespectful behaviour. This includes but is not limited to: Racism, Sexism, Classism, Ableism, Homophobia, Transphobia, Biphobia, Acephobia, Discrimination, Name Calling, Making Threats, Creating False Reports, Insulting Users, Making Personal Attacks, or Swearing at Users.<br><br>We take accusations of this kind very seriously. If you or another member are being harassed, please bring it to Moderator Mail right away so a full investigation can be conducted.</p><br>';
echo '<p><strong>2. No Spamming Allowed</strong><br><br>Please do not spam our website, discord, or social media. Examples of this include:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Sending Multiple Letters to Users</li>';
echo '<li style="margin-bottom:.5rem">Posting Repeat Critterweb Topics</li>';
echo '<li style="margin-bottom:.5rem">Posting the Same Reply Multiple Times</li>';
echo '<li style="margin-bottom:.5rem">Spamming Messages in Chat</li>';
echo '<li style="margin-bottom:.5rem">Spamming Emojis/Stickers in Chat</li>';
echo '<li style="margin-bottom:.5rem">Using Critterweb for Private Conversations</li>';
echo '<li style="margin-bottom:.5rem">Sending the Same Message to Multiple Users</li>';
echo '</ul>';
echo '<p><strong>3. No Begging Allowed</strong><br><br>Never beg for items or pressure a user to give you an item. Examples of this include:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Asking for Gifts on your Birthday or Events</li>';
echo '<li style="margin-bottom:.5rem">Asking for Items for Free</li>';
echo '<li style="margin-bottom:.5rem">Asking a User to Give you an Item/Snoozeling They Own</li>';
echo '<li style="margin-bottom:.5rem">Asking a User to Put a Snoozeling up for Adoption</li>';
echo '<li style="margin-bottom:.5rem">Asking Mods/Staff for Kindness Coins</li>';
echo '<li style="margin-bottom:.5rem">Asking Mods/Staff for Items</li>';
echo '</ul>';
echo '<p><strong>4. Do not write in any language other than English.</strong><br><br>We don\'t mean any harm by this rule, but currently our moderators and staff only speak English. <br><br>Therefore, we can only moderate when it comes to content in the English language. <br><br>Please only use english when interactions with the website and discord, including critterweb posts, private messages, comments, interactions, and chatbox messages.</p><br>';
echo '<p><strong>5. Do not Troll / Attempt to Troll</strong><br><br>This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Posting Controversial Content to Upset / Anger Users</li>';
echo '<li style="margin-bottom:.5rem">Posting Content for Shock Value</li>';
echo '<li style="margin-bottom:.5rem">Personal attacks against any member, staff member, or Snoozelings</li>';
echo '<li style="margin-bottom:.5rem">Baiting members into breaking rules to report them</li>';
echo '</ul>';
echo '<p><strong>6. Mini-Modding is Prohibited</strong><br><br>This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Attempting to Control what Others Post</li>';
echo '<li style="margin-bottom:.5rem">Issuing Warnings to Other Members</li>';
echo '<li style="margin-bottom:.5rem">Telling a Moderator About to Moderate</li>';
echo '<li style="margin-bottom:.5rem">Trying to Bribe Moderators</li>';
echo '<li style="margin-bottom:.5rem">Bribing New Players to Join</li>';
echo '<li style="margin-bottom:.5rem">Private Messaging Moderators Outside of Moderator Mailbox</li>';
echo '</ul>';
echo '<p><strong>7. Do Not Post for Other Members</strong><br><br>Do not post critterwebs or send mail on behalf of other users, including active users and banned users.</p><br>';
echo '<p><strong>8. Bribes are Not Allowed</strong><br><br>You are not allowed to bribe users for any reason. It does not matter what the bribe is: artwork, currency, items, snoozelings, etc. This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Bribing Users to Vote on Polls</li>';
echo '<li style="margin-bottom:.5rem">Bribing to Vote a Certain Way</li>';
echo '<li style="margin-bottom:.5rem">Offering Bribes to Moderators for Kindness Coins</li>';
echo '<li style="margin-bottom:.5rem">Offering Bribes to Moderators for Moderator Decisions</li>';
echo '<li style="margin-bottom:.5rem">Offering Bribes for Friend Requests</li>';
echo '<li style="margin-bottom:.5rem">Bribing a User for a Giveaway Prize</li>';
echo '</ul>';
echo '<p><strong>9. Patience is Key</strong><br><br>Please be patient with all members. Some may not be able to reply right away. Some may forget to reply. Some may just decide not to reply. All these players should be treated with respect and kindness. <br><br>This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Moderator Mailbox</li>';
echo '<li style="margin-bottom:.5rem">Private Messages</li>';
echo '<li style="margin-bottom:.5rem">Critterweb Posts</li>';
echo '<li style="margin-bottom:.5rem">Chat Messages on Discord</li>';
echo '<li style="margin-bottom:.5rem">Roleplays</li>';
echo '</ul>';
echo '<p><strong>10. Listen to Staff</strong><br><br>If a staff asks you to stop a conversation, you must listen. If a staff comments on a critterweb topic with instructions, you must listen. If a staff finds a user to be scamming, you may be asked to return items or currency. Staff are just doing their best to keep the website and discord running smoothly.<br><br>All staff decisions are final. This includes developers, administrators, moderators, and discord moderators. If you have a problem with a staff decision, you can ask for your moderator mailbox to be escalated or bring the issue to the attention of <a href="https://snoozelings.com/profile?id=1">Slothie</a> to be investigated.</p><br>';
echo '<p><strong>11. Let Players Play How They Want</strong><br><br>As long as players aren\'t hurting anyone, they are welcome to play the game how they want.<br><br>Do not do any of the following without being asked first:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Offer Opinions Randomly</li>';
echo '<li style="margin-bottom:.5rem">Tell People Which Snoozeling to Choose</li>';
echo '<li style="margin-bottom:.5rem">Tell People How to Use Items</li>';
echo '<li style="margin-bottom:.5rem">Tell People how to run Giveaways</li>';
echo '<li style="margin-bottom:.5rem">Give Life Advice</li>';
echo '<li style="margin-bottom:.5rem">Tell Moderators how to Moderate</li>';
echo '<li style="margin-bottom:.5rem">Be Rude to Roleplayers</li>';
echo '<li style="margin-bottom:.5rem">Tell Roleplayers Their RP is Non-Canons/Wrong/Etc</li>';
echo '<li style="margin-bottom:.5rem">Telling People to not Create new Snoozeings Based on Past Inspires</li>';
echo '</ul>';
echo '<h4 id="artwork">2. Artwork Rules</h4><br>';
echo '<p><strong>12. AI Artwork is Not Allowed</strong><br><br>Artificially generated artwork or writing is not allowed on Snoozlings in any capacity. If you find AI generated content, please report it to Moderator Mailbox right away so it can be removed.<br><br>This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Sharing AI Artwork</li>';
echo '<li style="margin-bottom:.5rem">Selling AI Generated Adopts</li>';
echo '<li style="margin-bottom:.5rem">AI Generated Commissions</li>';
echo '<li style="margin-bottom:.5rem">AI Generated Free Art Giveaways</li>';
echo '<li style="margin-bottom:.5rem">Linking to AI Artists Off Site</li>';
echo '<li style="margin-bottom:.5rem">Linking to AI Artwork Generators</li>';
echo '<li style="margin-bottom:.5rem">AI Artwork Creation Guides</li>';
echo '</ul>';
echo '<p><strong>13. Art Theft is Not Allowed</strong><br><br>We do not allow players to steal artwork and claim it as their own. This also includes:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Tracing Other Artwork</li>';
echo '<li style="margin-bottom:.5rem">Tracing Stock Photos Without Proper Credit</li>';
echo '<li style="margin-bottom:.5rem">Copying Other Artwork</li>';
echo '<li style="margin-bottom:.5rem">Claiming Artwork as Your Own</li>';
echo '<li style="margin-bottom:.5rem">Creating Splash Artwork</li>';
echo '<li style="margin-bottom:.5rem">Using Patterns/Bases That you Didn\'t Purchase</li>';
echo '<li style="margin-bottom:.5rem">Selling Adopts from "Custom Creator" or "Doll Maker" Tools</li>';
echo '</ul>';
echo '<p><strong>14. Bases & Patterns Need to Be Credited</strong><br><br>All base files on adoptables need to be credited to the original artist. For adoptable/artwork bases, a link must be provided to where you found/purchased the base.<br><br>If making 3D artwork - <i>such as 3D modeling, plushies, crochet, 3D prints, etc</i> - all bases need to be credited. A link to where you purchased the base must be provided. <br><br>If that pattern/base is no longer for sale or was private use only, a link to their social media or shop can be substituted. If all their social media has been destroyed, a name can be provided.<br><br>While not necessary, if you made the base/pattern yourself, it is helpful to moderators for you to mention "Base by Myself" or "Pattern by Myself". Otherwise, staff may contact you with questions.</p><br>';
echo '<p><strong>15. Adoptables & Base Fills</strong><br><br>Adoptables and Base Fills are allowed on Snoozelings, but we do have some guidelines you must abide by.</p>';
echo '<ol style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">You Must Credit the Base Artist</li>';
echo '<li style="margin-bottom:.5rem">You Must Link to Where you Found/Bought the Base</li>';
echo '<li style="margin-bottom:.5rem">You Cannot Trade for Snoozeling Items/Currency/Snoozelings/Etc</li>';
echo '<li style="margin-bottom:.5rem">For Paid Bases, You Must Be Able to Provide Proof you Purchased the Base</li>';
echo '<li style="margin-bottom:.5rem">If Doing them for Free, you Cannot Accept Bribes</li>';
echo '<li style="margin-bottom:.5rem">You Cannot Sell Adopts Created from the Snoozelings Maker</li>';
echo '</ol>';
echo '<p><strong>16. Selling Artwork for Money</strong><br><br>Selling artwork for currency is allowed. Please Keep in Mind:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Snoozelings has No Control on Outside Payment Processors</li>';
echo '<li style="margin-bottom:.5rem">In the case of a scam, it is up to you to follow up with payment processors and/or your bank</li>';
echo '<li style="margin-bottom:.5rem">Always report scamming to Snoozelings; we will investigate and issue bans accordingly</li>';
echo '<li style="margin-bottom:.5rem">Never Pay Friends & Family, Use Cashapp, or Other Nonrefundable Sources</li>';
echo '<li style="margin-bottom:.5rem">Never Pay with Giftcards, Deviantart Points, Nitro, Other Website Currency, etc</li>';
echo '<li style="margin-bottom:.5rem">Good Services: Kofi Shops, Etsy Shops, Paypal Goods & Services</li>';
echo '</ul>';
echo '<p><strong>17. Selling Art for In-Game Assets is Not Allowed</strong><br><br>You are not allowed to trade artwork for any snoozelings in-game items, currency, pets, etc.<br><br>This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Payments for Commissions</li>';
echo '<li style="margin-bottom:.5rem">Payments for Services</li>';
echo '<li style="margin-bottom:.5rem">Payments for Adopts</li>';
echo '<li style="margin-bottom:.5rem">Payments for Characters</li>';
echo '<li style="margin-bottom:.5rem">Payments for Video Editing</li>';
echo '<li style="margin-bottom:.5rem">Payments for Voice Acting</li>';
echo '<li style="margin-bottom:.5rem">Payments for Base Fills</li>';
echo '</ul>';
echo '<p><strong>18. All Artwork Must be 13+ Rated</strong><br><br>The following subjects are not allowed in artwork:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Nipples of Any Gender</li>';
echo '<li style="margin-bottom:.5rem">Genitals of Any Gender</li>';
echo '<li style="margin-bottom:.5rem">Sexual Themes</li>';
echo '<li style="margin-bottom:.5rem">Gore of Any Type (Normal, Candy, Etc)</li>';
echo '<li style="margin-bottom:.5rem">Any Type of Self Harm</li>';
echo '<li style="margin-bottom:.5rem">Kink Content</li>';
echo '<li style="margin-bottom:.5rem">Drugs of Any Type</li>';
echo '<li style="margin-bottom:.5rem">Alcohol of Any Type</li>';
echo '<li style="margin-bottom:.5rem">Anything with Illegal Activities</li>';
echo '<li style="margin-bottom:.5rem">Directly Linking to Websites Containing Anything Above</li>';
echo '</ul>';
echo '<h4 id="account">3. Account Guidelines</h4><br>';
echo '<p><strong>19. Only 1 Account is Permitted Per Player</strong><br><br>No user is allowed to have two or more accounts for any reason. No exceptions.<br><br>If a member is found with a second account, the second account will be banned without any warnings. The main account will also be noted as previously multi-accounting.<br><br>If a user is found breaking this rule multiple times, the main account may also be banned.</p><br>';
echo '<p><strong>20. Sharing Accounts is Not Allowed</strong><br><br>Game accounts are for your personal use only.<br><br>You are not allowed to transfer or share use of your account with anyone: friends, family membors, twins, etc. <br><br>All accounts contain private medical information that should never be shared. Due to this, accounts found to be shared will be locked down to prevent sharing of this information.<br><br><i>Members with Dissaciative Identity Disorder may contact staff to have a note put on their account if they are concerned alters on their account may look like account sharing. While they still may not share accounts with other people, alters in the same body are okay. We will do our best to accomodate those with this condition.</i></p>';
echo '<h4 id="scamming">4. Cheating & Scamming</h4><br>';
echo '<p><strong>21. Scamming is Not Allowed in Any Capacity</strong><br><br>When scamming is suspected, a report should be made to Moderator Mail. That way the moderators can do a full investigation, review all evidence, and take the proper actions. <br><br>Scamming includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Not Finishing Art Commissions</li>';
echo '<li style="margin-bottom:.5rem">Not Shipping Orders</li>';
echo '<li style="margin-bottom:.5rem">Selling Stolen Adopts</li>';
echo '<li style="margin-bottom:.5rem">Not Completing Art Trades</li>';
echo '<li style="margin-bottom:.5rem">Selling AI Generated Artwork</li>';
echo '<li style="margin-bottom:.5rem">Tricking Members for Items/Currency/Snoozelings/etc.</li>';
echo '<li style="margin-bottom:.5rem">Asking for Payment for Stuff you Previously Agreed was Free</li>';
echo '</ul>';
echo '<p><strong>22. Do not Exploit Bugs or Glitches</strong><br><br>Users must report any bugs or glitches to Moderator Mail. <br><br>Never share bugs or glitches on discord, critterbox, or in private messages.<br><br>Users found to be exploiting bugs or glitches on purpose will be punished on a case by case basis. This may include warnings, removal of items, or being banned. If you gain an item through a bug or exploit by mistake, let us know through Moderator Mail and no punishment will be taken.</p><br>';
echo '<p><strong>23. Use of Scripts to Play or Cheat are Prohibited</strong><br><br>"Script" on this website is defined as any program used to automate processes on the site, usually written in, though not limited to, javascript, PERL, CGI, PHP, or ASP.<br><br>Exceptions to this rule are:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Adblockers</li>';
echo '<li style="margin-bottom:.5rem">Form Auto Fillers</li>';
echo '<li style="margin-bottom:.5rem">Add Ons that Adjust Appearance Only</li>';
echo '<li style="margin-bottom:.5rem">Auto Refreshers**</li>';
echo '</ul>';
echo '<p>**Auto Refreshers are only allowed in small uses. They can only refresh once every 15 seconds per account. Any more than that is breaking terms. We are allowing this to help people with hand injuries.<br><br><strong>If this becomes a problem for the servers, auto refreshers may become banned. Use them wisely.</strong></p>';
echo '<h4 id="roleplay">5. Roleplaying Regulations</h4><br>';
echo '<p><strong>24. Keep Roleplaying to the Appropriate Areas</strong><br><br>Roleplay is only allowed in the following areas:</p>';
echo '<ol style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Critterbox Roleplaying Area</li>';
echo '<li style="margin-bottom:.5rem">Private Messages with Permission</li>';
echo '</ol>';
echo '<p><strong>25. Roleplay Must Be Suitable for Ages 13+</strong><br><br>The following subjects are not allowed in critterbox or private message roleplays:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Nipples of Any Gender</li>';
echo '<li style="margin-bottom:.5rem">Genitals of Any Gender</li>';
echo '<li style="margin-bottom:.5rem">Sexual Themes</li>';
echo '<li style="margin-bottom:.5rem">Gore of Any Type (Normal, Candy, Etc)</li>';
echo '<li style="margin-bottom:.5rem">Any Type of Self Harm</li>';
echo '<li style="margin-bottom:.5rem">Kink Content</li>';
echo '<li style="margin-bottom:.5rem">Drugs of Any Type</li>';
echo '<li style="margin-bottom:.5rem">Alcohol of Any Type</li>';
echo '<li style="margin-bottom:.5rem">Anything with Illegal Activities</li>';
echo '<li style="margin-bottom:.5rem">Relationships with Questionable Age Ranges or Power Dynamics</li>';
echo '</ul>';
echo '<h4 id="forbidden">6. Forbidden Topics</h4><br>';
echo '<p><strong>26. Forbidden Topics</strong><br><br>To create a safe space on Snoozelings, any post with forbidden content can be removed at anytime.<br><br>The list includes but is not limited to:';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">AI / Artificial intelligence Artwork</li>';
echo '<li style="margin-bottom:.5rem">NFT / Non-fungible Tokens / Bitcoin / Related Topics</li>';
echo '<li style="margin-bottom:.5rem">Sexual Content</li>';
echo '<li style="margin-bottom:.5rem">Kink Content</li>';
echo '<li style="margin-bottom:.5rem">Gore of Any Type (Normal, Candy, Etc)</li>';
echo '<li style="margin-bottom:.5rem">Self Harm of Any Kind</li>';
echo '<li style="margin-bottom:.5rem">Drugs of Any Type</li>';
echo '<li style="margin-bottom:.5rem">Alcohol of Any Type</li>';
echo '<li style="margin-bottom:.5rem">Any Illegal Activities</li>';
echo '<li style="margin-bottom:.5rem">Guns / Gun Violence / Shootings</li>';
echo '<li style="margin-bottom:.5rem">Politics / Religion</li>';
echo '<li style="margin-bottom:.5rem">War / Genocide</li>';
echo '<li style="margin-bottom:.5rem">Animal Abuse</li>';
echo '<li style="margin-bottom:.5rem">Human Abuse</li>';
echo '<li style="margin-bottom:.5rem">Youtuber / Tiktok Drama</li>';
echo '<li style="margin-bottom:.5rem">Social Media Drama</li>';
echo '<li style="margin-bottom:.5rem">Fandom Drama</li>';
echo '<li style="margin-bottom:.5rem">Relationships with Questionable Age Ranges or Power Dynamics</li>';
echo '</ul>';
echo '<h4 id="trading">7. Trading Regulations</h4><br>';
echo '<p><strong>27. Trading Snoozeling In-Game Items is Forbidden</strong><br><br>Trading Snoozelings Currency/Items/Snoozelings/Etc for anything is not allowed.<br><br>This includes but is not limited to:</p>';
echo '<ul style="font-size:1.6rem;">';
echo '<li style="margin-bottom:.5rem">Other Snoozeling Currency/Items/Snoozelings/Etc.</li>';
echo '<li style="margin-bottom:.5rem">In-Game Items/Currency/Pets from Other Websites</li>';
echo '<li style="margin-bottom:.5rem">Real Life Currency or Credit</li>';
echo '<li style="margin-bottom:.5rem">Gift Cards for Any Website</li>';
echo '<li style="margin-bottom:.5rem">Deviantart Points or Other Web Currencies</li>';
echo '<li style="margin-bottom:.5rem">Artwork of Any Kind</li>';
echo '<li style="margin-bottom:.5rem">Discord Nitro or Other Subscriptions</li>';
echo '</ul>';
echo '<p><strong>28. Selling Accounts are Not Allowed</strong><br><br>Selling or trading your account for anything is not allowed. Sold accounts will be permanently banned.</p>';
echo '</div>';
















