<?php

echo '<h3>TERMS OF SERVICE</h3>';
echo '<p><i>Last Updated November 29, 2023</i></p><br>';
echo '<div class="privacy" style="width: 90%; margin-left: 2rem; margin-right: auto;text-align: left;">';
echo '<p>Below are the following terms and conditions put in place for <a href="index">https://snoozelings.com/</a>. By registering an account with Snoozelings, you must agree to these terms and conditions, as well as the <a href="privacy">Privacy Policy</a> and <a href="conduct">Code of Conduct</a>. By logging in and playing, you continuously agree to the terms.<br><br>The terms of service may be updated in the future. If this is done, there will be a sitewide announcement. You are urged to check this page every so often to be up to date on the current terms. Exceptions will not be made for members who break the terms of service because they were not aware of policy changes. <br><br>If any of these terms or conditions are broken, various actions may be taken by the developers. These may included but are not limited to: warnings, temporary bans, lifetime bans, ip bans, restrictions of your account.<br><br></p>';
echo '<p style="text-align: center;"><strong>This policy may change at any time. <br>Please check this page every so often to ensure you agree with any changes.</strong></p><br>';
echo '<h4>1. Definitions</h4>';
echo '<p><strong>"Content"</strong> refers to any kind of information stored by the game. This includes but is not limited to private messages, bulletin board posts, journal entries, user information, comments, images, etc.<br><br><strong>"Virtual Currency"</strong> refers to in-game currency, including "Gold Coins" and "Kindness Coins". All currency has no real world value. There is no premium currency for Snoozelings at this time.<br><br><strong>"The Game"</strong> refers to the entire website of Snoozelings and anyway you may interact with the game. This also includes any possible future software like a mobile application, as well as our official Discord Server and other social media.<br><br><strong>"User"</strong> refers to anyone using the website, whether or not they are registered. It also includes any users of our official Discord Server, social media pages, and any possible future mobile applications.<br><br><strong>"In-Game Items"</strong> refers to any virtual items collected within the game. This includes but is not limited to snoozelings pets, minipets, gold coins, kindness coins, and items.<br><br><strong>"Staff"</strong> refers to staff members that run the game. This may include but is not limited to lead developers, developers, moderators, administrators, etc.</p>';
echo '<h4>2. Age of Registration</h4>';
echo '<p>The game is only available to users who meet the minimum legal age of consent for data processing, collection, and use in their main country of residence.<br><br> The age for digital consent is a minimum of 13 years of age in the USA, a minimum of 16 years of age in Canada, and a range of 13-16 years of age in European countries. We do not collect your country of residence at time of registration, but by attempting to use our service, you are agreeing that you meet the minimum age of digital consent in your country. If you change countries, you are bound to the laws of your new place of residence.<br><br> If you are found to be under the minimum age, your account will be terminated without notice. Recovery of accounts once you are of age will be on a case by case basis and at discretion of staff.<br><br>Snoozelings has a minimum age of 13 years old. If your country has no age of consent for digital services or your country has an age under 13 years old, you still cannot use our services unless you are 13 years old or older.</p>';
echo '<h4>3. Account</h4>';
echo '<p>It is the player\'s responsibility to create their own username and password. Please make sure it is as secure as possible. Do not share your login information with others. Always log out of your account when using a public network. We are not responsible for stolen acccounts due to sharing information or mistakes.<br><br>Users are only allowed one account per person. Making multiple accounts for any reason is not allowed. This includes but is not limited to: getting extra currency, getting extra items, snoring snoozelings to bypass account limitations, taking advantage of events, etc. If you are found multiaccounting, any accounts besides your first account will be banned and your 1st account will recieve a warning.<br><br>Transfer of accounts is strictely forbidden. This includes but is not limited to: transfering accounts, trading accounts, selling accounts for money/art/etc. Accounts found to be traded/sold will be banned.<br><br>Your account can be terminated at anytime for breaking the terms of service or code of conduct. We do not need to notify you in this instance. Bans will not be discussed publicly by staff, but information can be requested by submitting a ticket.</p>';
echo '<h4>4. Conduct</h4>';
echo '<p>As a Snoozelings member, you agree to follow the <a href="conduct">Code of Conduct</a>.<br><br>You may not use this website for any unlawful purposes. This includes but is not limited to: posting illegal content, distributing illegal content, promoting illegal content, threats of harm, etc<br><br>The use of bots, scripts, or third party softwares that may harm the website is unpermitted. Exceptions to this are adblockers, any scripts that adjust visuals without contacting our servers, form auto fillers, or page refreshers, as long as they only refresh once per 15 seconds maximum. Any more often than that is breaking terms.<br><br>Exploitation of bugs, glitches, or loopholes is not permitted. If you discover a bug that may be game breaking or that can be used to give players an unfair advantage, please do not share it. Do not post it anywhere in the game, on our discord, or social media. Report it to staff through a ticket as soon as posisble.<br><br>Cross-Site trading for Snoozelings in-game items/pets are not allowed at this time. We cannot support these trades if they happen to fall through. It also goes against our anti dog-eat-dog economy stance. This includes all websites, games, items, and currencies. No exceptions.<br><br>While we do allow lending between accounts (pets, currency, items), we may not be able to recover your in-game items in the case of abandonment or refusal to remove items, especially if the item has been used. Lending is "trade at your own risk". Staff can review evidence and may be able to intervene, but it is not guarenteed.<br><br>We are not responsible for any personal data shared through the game or off site. This includes but is not limited to: names, emails, social media usernames, chat service usernames, place of residence, ages, etc.<br><br>Users are not allowed to impersonate other members. This includes but is not limited to: staff members, other members, social media influencers, twitch streamers, etc. If staff find out that you are claiming to be someone you are not, it may result in account terminiation.</p>';
echo '<h4>5. Links</h4>';
echo '<p>Snoozelings may include links to other websites provided by the game, users, or advertisers. Snoozelings is not responsible for the content, sales or interactions found on these websites. Furthermore, Snoozelings makes no guarentee for these websites when it comes to safety, information, products, or services. <br><br>We are not responsible for damage caused by other websites or liable for any loss incurred as a result of damage or dealings from linked websites. Please browse the internet at your own risk.<br><br>Users are allowed to link to external websites including user shops, social media, sources of information and other types of links. They may not link to anything harmful or unlawful. Whether or not specific websites are allowed are at the descretion of staff. </p>';
echo '<h4>6. Copyright</h4>';
echo '<p>All of the contents and elements of Snoozelings, unless otherwise stated, are copyright 2023 of Slothie Studios/Snoozelings, including images, pets, ideas, and plots.<br><br>User content including - but not limited to - forum posts, private messages, pet pages, custom skins, and any other content submitted to the game is subject to the following agreement: By submitting content to Snoozelings, the user warrants that they have the full legal rights of content submitted, and thereby grant Snoozelings all rights to use any and all submitted content, without limitations, for the game.<br><br>Upon submitting content to Snoozelings such as skins, artwork, etc. you grant Snoozelings a non-exclusive, royalty-free license to copy, reproduce, modify, change, transmit, adapt, distribute, re-format, store, broadcast, exhibit, and create derivative works as needed from such content, as well as to publicly display your content in game. You also agree that you will not recieve compensation unless formally agreed upon in writing.<br><br>Creating fanart of Snoozelings content is allowed, but you cannot use any fanart of the brand - including the logo - for profit without recieving permission from the Snoozelings team. We are a small team and we ask this out of respect, as our own merchandise is what keeps the site afloat.<br><br>The exception to the above rule is one off commissions of handmade artwork. This includes 2D artwork like icons, chibis, etc. It also includes 3D artwork like plush making, kigurumis, sweaters, rug tufting, fursuits, needle felts, etc. Once again, this is for "one of a kind" commission exceptions only. They give you money and you create art of their specific snoozeling character. <br><br>Artwork made in batches larger than 3 items or in factories are still not permitted. This includes but is not limited to: t-shirts, enamel pins, plushies, acrylic keychains, glass etching, stickers, magnets, etc. Please contact us first if this is something you would like to pursue. <br><br>Images from the game cannot be used for profit in any way including: photoshop edits, page coding, self projects, wiki pages, or artwork such as writing, crafting, 2d artwork, etc. This includes all item images, pet images, logo images, the brand name "Snoozelings", and any other site assets. This rule applies to any kind of currencies including real life currencies and in-game currencies.<br><br></p>';
echo '<h4>7. Purchases</h4>';
echo '<p>Snoozelings does not have a virtual currency at this time.<br><br>Snoozelings does offer a premium monthly membership to it\'s users. This includes benefits that may be taken away or paused at the end of the membership period. Membership can be restarted at anytime to take advantage of these features once again.<br><br>Snoozelings does offer merchandise for sale to fund the game. All merchandise sales are final, including preorders that may take months to ship. Snoozelings will keep all members updated with production times, but Snoozelings puts large sums of money into production and game development and may not be able to refund payments by discretion of staff. Please be sure in your purchase before purchasing.<br><br>Use of stolen credit cards or chargebacks may result in account suspension or ban. This punishes the game as we lose additional money on chargebacks and too many chargebacks cause loss of payment processing services. We must take this very seriously and there are no exceptions to this rule.<br><br>Refunds are not permitted on premium memberships, early access accounts, or custom items such as skins, poses, outfits, colors, etc.</p>';
echo '<h4>8. Game Function</h4>';
echo '<p>We cannot guarentee the game will be uninterrupted or error-free during playtime. We are a new game developer and will be doing our best to fix bugs in a timely fashion, but during early access a rough product is to be expected. We are not responsible for any loss of account-related data due to technical errors or account rollbacks. Any member attacking staff over bug related issues is at risk of being banned.<br><br>Without notice, we may at anytime, suspend the game for repair, maitenance, improvement, server fixes, to prevent attacks, or any other technical reason. Downtime cannot be helped as we must prioritize the state of the game at any given time.<br><br>Changes may be made to the game at anytime that may change mechanics or artwork within the game. Refunds will not be provided if you disagree with changes.<br><br>Dates for future updates are an estimate and can change depending on many circumstances. Staff will do our best to keep players updated, but harassment over game delays will not be tolerated. We are all doing our best.</p>';
echo '</div>';




































